version: 0.0
os: linux
files:
    -source: /target/ROOT.war
    destination: /usr/share/tomcat7/webapps
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh    
      runas: root
    - location: scripts/stop-server.sh
      runas: root	
  AfterInstall:
    - location: scripts/after-install.sh
      runas: root
