version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh    
      runas: root
    - location: scripts/stop-server.sh
      runas: root	
  AfterInstall:
    - location: scripts/after-install.sh
      runas: root
